services:
  web:
#    build: .
    image: php:apache #temporaire, le temps de faire marcher oracle
    container_name: apache_web
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes: #temporaire, le temps de faire marcher oracle
      - ./public_html:/var/www/html #temporaire, le temps de faire marcher oracle
#    depends_on:
#      - oracle
#
#  oracle:
#    image: container-registry.oracle.com/database/free:latest
#    container_name: oracle_db
#    restart: unless-stopped
#    environment:
#      - ORACLE_PWD=oracle
#      - ORACLE_CHARACTERSET=AL32UTF8
#    ports:
#      - "1521:1521"
#      - "5500:5500"
#    volumes:
#      - ./oracle_data:/opt/oracle/oradata